// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt9V1c4f0Ey7W9JzivUPOVrX4INISJm7Y',
    appId: '1:42815676315:web:6189fbdcb316e361108b3e',
    messagingSenderId: '42815676315',
    projectId: 'matsue-castle-chat-bot',
    authDomain: 'matsue-castle-chat-bot.firebaseapp.com',
    storageBucket: 'matsue-castle-chat-bot.firebasestorage.app',
    measurementId: 'G-VQ2M4KWYMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZN7giZZPKXFFr_pBKEsgoWhwTTI778d0',
    appId: '1:42815676315:android:acb21a16eaa08b4d108b3e',
    messagingSenderId: '42815676315',
    projectId: 'matsue-castle-chat-bot',
    storageBucket: 'matsue-castle-chat-bot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRZ1HmSNbm2xQyr6WnlJDy4UOO9Yu7L5U',
    appId: '1:42815676315:ios:657b77261f85b5ff108b3e',
    messagingSenderId: '42815676315',
    projectId: 'matsue-castle-chat-bot',
    storageBucket: 'matsue-castle-chat-bot.firebasestorage.app',
    iosBundleId: 'com.github.toruishihara.aiShopList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRZ1HmSNbm2xQyr6WnlJDy4UOO9Yu7L5U',
    appId: '1:42815676315:ios:7a20a57bacd34f1c108b3e',
    messagingSenderId: '42815676315',
    projectId: 'matsue-castle-chat-bot',
    storageBucket: 'matsue-castle-chat-bot.firebasestorage.app',
    iosBundleId: 'com.example.aiShopList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt9V1c4f0Ey7W9JzivUPOVrX4INISJm7Y',
    appId: '1:42815676315:web:d81886b43673c6fd108b3e',
    messagingSenderId: '42815676315',
    projectId: 'matsue-castle-chat-bot',
    authDomain: 'matsue-castle-chat-bot.firebaseapp.com',
    storageBucket: 'matsue-castle-chat-bot.firebasestorage.app',
    measurementId: 'G-WSRRNZGGCZ',
  );
}
