name: matsue_castle_chat_bot
description: "Chatbot with RAG for Matsue Castle."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  record: ^6.1.1
  flutter_tts: ^3.8.3
  path_provider: ^2.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0
  firebase_core: ^3.7.0
  firebase_crashlytics: ^4.1.0
  firebase_analytics: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.11
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/matsue_castle_nobg.png"
  adaptive_icon_foreground: "assets/icon/matsue_castle_nobg.png"
  adaptive_icon_background: "#00000000"